# Generated by Django 3.1.3 on 2020-11-02 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenRoom',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('finish_time', models.DateTimeField(verbose_name='Время окончания')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Спикер')),
            ],
            options={
                'verbose_name': 'открытая комната',
            },
        ),
        migrations.CreateModel(
            name='PasswordProtectedRoom',
            fields=[
                ('openroom_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='videochat.openroom')),
                ('password', models.TextField(max_length=32, verbose_name='Пароль комнаты')),
            ],
            options={
                'verbose_name': 'комната с паролем',
            },
            bases=('videochat.openroom',),
        ),
        migrations.CreateModel(
            name='PrivateRoom',
            fields=[
                ('openroom_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='videochat.openroom')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'личная комната',
            },
            bases=('videochat.openroom',),
        ),
    ]
