# Generated by Django 3.1.3 on 2020-11-03 11:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('videochat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openroom',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passwordprotectedroom',
            name='password',
            field=models.CharField(max_length=32, verbose_name='Пароль комнаты'),
        ),
    ]
